dist: trusty
sudo: required
language: node_js
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
cache:
  directories:
    - tour-of-heroes/node_modules
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - cd tour-of-heroes
  - npm install
script:
  - npm run lint
  - npm run test -- --watch=false
  - npm run travis